#name: Build CI

#on: push

#jobs:
 # build:
    #runs-on: ubuntu-latest        # Betriebssystem wo es laufen soll ( bei Github)


   # steps:
     # - uses: actions/checkout@v3
     # - uses: actions/setup-java@v3                   #läuft mit java
     #   with:                                         # mit welcher Version
      #    java-version: "18"                          # mit java version 18
      #    distribution: "temurin"                     # von wo die version oracle usw. in den falle temurin
     # - name:  Build Project                      # nur eine benennung
     #   run:  mvn -B package --file pom.xml     # -B steht für batge mode und ist dafür nur das nötigste auszugeben

name: Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
      - name: Build Project
        run: mvn -B package --file pom.xml
